### ISSUE TITLE
x-ratelimit-remaining is causing Error

### ISSUE THREAD

**Issue by fatshotty** [gajus/tmdb#2]
Hi,
I think TMDb api server is no longer returning `x-ratelimit-remaining` response header.
This is causing `UnhandledError()` , but body response is correctly fullfilled.

Is this only me?

**Comment by gajus** [comment]
No, I noticed that my request are failing too. Probably this issue too.

Should be easy fix – are you available to contribute?

**Comment by fatshotty** [comment]
tested and it works now
many thanks
